# Generated by Django 6.0.4 on 2026-04-22 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('casa', 'Casa'), ('depto', 'Departamento'), ('terreno', 'Terreno')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ciudad', models.CharField(max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie', models.PositiveIntegerField()),
                ('dormitorios', models.PositiveIntegerField(default=0)),
                ('banos', models.PositiveIntegerField(default=0)),
                ('cochera', models.BooleanField(default=False)),
                ('descripcion', models.TextField()),
                ('foto_principal', models.ImageField(upload_to='propiedades/')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('pausada', 'Pausada')], default='activa', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
