# Generated by Django 6.0.4 on 2026-05-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="ubicacion",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
