# Generated by Django 6.0.4 on 2026-05-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0002_propiedad_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="departamento",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Asunción", "Asunción"),
                    ("Central", "Central"),
                    ("Alto Paraguay", "Alto Paraguay"),
                    ("Alto Paraná", "Alto Paraná"),
                    ("Amambay", "Amambay"),
                    ("Boquerón", "Boquerón"),
                    ("Caaguazú", "Caaguazú"),
                    ("Caazapá", "Caazapá"),
                    ("Canindeyú", "Canindeyú"),
                    ("Concepción", "Concepción"),
                    ("Cordillera", "Cordillera"),
                    ("Guairá", "Guairá"),
                    ("Itapúa", "Itapúa"),
                    ("Misiones", "Misiones"),
                    ("Ñeembucú", "Ñeembucú"),
                    ("Paraguarí", "Paraguarí"),
                    ("Presidente Hayes", "Presidente Hayes"),
                    ("San Pedro", "San Pedro"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="moneda",
            field=models.CharField(
                choices=[("USD", "Dólar (USD)"), ("PYG", "Guaraníes (PYG)")],
                default="USD",
                max_length=3,
            ),
        ),
    ]
