# Generated by Django 4.2.25 on 2026-06-23 03:02

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0003_propiedad_departamento_propiedad_moneda"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propiedad",
            options={"ordering": ["-creado"]},
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="precio",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("1"))],
            ),
        ),
        migrations.AlterField(
            model_name="propiedad",
            name="superficie",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
