# Generated by Django 6.0.4 on 2026-06-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propiedades", "0004_alter_propiedad_options_alter_propiedad_precio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="propiedad",
            name="latitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="propiedad",
            name="longitud",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
