# Generated by Django 4.2.25 on 2026-06-23 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contactos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contacto",
            options={"ordering": ["-creado"]},
        ),
        migrations.AddField(
            model_name="contacto",
            name="comprador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mensajes_enviados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
